/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ihm;
import javax.swing.ImageIcon;
import java.awt.Image;
import javax.swing.*;
import java.awt.*;



/**
 *
 * @author hp
 */
public class FenetreGlobale extends javax.swing.JFrame {

    /**
     * Creates new form FenetreGlobale
     */
    public FenetreGlobale() {
       initComponents();
       ImageIcon icon = new ImageIcon(getClass().getResource("/ihm/images/TTR.png"));
       Image img = icon.getImage().getScaledInstance(800, 400, Image.SCALE_SMOOTH);
       labelTTR.setIcon(new ImageIcon(img));
       
       ImageIcon iconPhoebe = new ImageIcon(getClass().getResource("/ihm/images/phrasesrecuparss1.png"));
       Image imgPhoebe = iconPhoebe.getImage().getScaledInstance(500, 400, Image.SCALE_SMOOTH);
       labelPhoebe.setIcon(new ImageIcon(imgPhoebe));

       ImageIcon iconRoss = new ImageIcon(getClass().getResource("/ihm/images/phrasesrecuparss2.png"));
       Image imgRoss = iconRoss.getImage().getScaledInstance(500, 400, Image.SCALE_SMOOTH);
       labelRoss.setIcon(new ImageIcon(imgRoss));
       // AJOUT DE L'ONGLET PROFIL LANGAGIER
       FenetreProfil fenetreProfil = new FenetreProfil();
       jTabbedPane1.setComponentAt(2, fenetreProfil.getContentPane()); // Onglet 3 = index 2
      
       ImageIcon iconPrincipal = new ImageIcon(getClass().getResource("/ihm/images/perso_principal.png"));
       Image imgPrincipal = iconPrincipal.getImage().getScaledInstance(800, 400, Image.SCALE_SMOOTH);
       labelPrincipal.setIcon(new ImageIcon(imgPrincipal));

           
       ImageIcon monicaIcon = new ImageIcon(getClass().getResource("/ihm/images/monica_emotion.png"));
       Image monicaResized = monicaIcon.getImage().getScaledInstance(600, 400, Image.SCALE_SMOOTH);
       emotionLabel1.setIcon(new ImageIcon(monicaResized));
       ImageIcon chandlerIcon = new ImageIcon(getClass().getResource("/ihm/images/chandler_emotion.png"));
       Image chandlerResized = chandlerIcon.getImage().getScaledInstance(600, 400, Image.SCALE_SMOOTH);
       emotionLabel2.setIcon(new ImageIcon(chandlerResized));

       // Heatmap 1
       ImageIcon iconHeatmap1 = new ImageIcon(getClass().getResource("/ihm/images/heatmap1.png"));
       Image imgHeatmap1 = iconHeatmap1.getImage().getScaledInstance(600, 450, Image.SCALE_SMOOTH);
       labelHeatmap1.setIcon(new ImageIcon(imgHeatmap1));

        // Heatmap 2
       ImageIcon iconHeatmap2 = new ImageIcon(getClass().getResource("/ihm/images/heatmap2.png"));
       Image imgHeatmap2 = iconHeatmap2.getImage().getScaledInstance(600, 450, Image.SCALE_SMOOTH);
       labelHeatmap2.setIcon(new ImageIcon(imgHeatmap2));
      
       ImageIcon iconTopK1 = new ImageIcon(getClass().getResource("/ihm/images/topk.png"));
       Image imgTopK1 = iconTopK1.getImage().getScaledInstance(600, 400, Image.SCALE_SMOOTH);
       labelTopK1.setIcon(new ImageIcon(imgTopK1));
       ImageIcon iconTopK2 = new ImageIcon(getClass().getResource("/ihm/images/topk2.png"));
       Image imgTopK2 = iconTopK2.getImage().getScaledInstance(600, 400, Image.SCALE_SMOOTH);
       labelTopK2.setIcon(new ImageIcon(imgTopK2));

  jTabbedPane1.addChangeListener(e -> {
    int selected = jTabbedPane1.getSelectedIndex();
    if (selected == 2) { // Onglet "Profil Langagier"
        new FenetreProfil().setVisible(true); // Ouvre la vraie interface
        jTabbedPane1.setSelectedIndex(0); // Revient à l’onglet TTR (index 0)
    }
});

    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        labelTTR = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        labelPhoebe = new javax.swing.JLabel();
        labelRoss = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea2 = new javax.swing.JTextArea();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTextArea3 = new javax.swing.JTextArea();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        labelPrincipal = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTextArea4 = new javax.swing.JTextArea();
        jPanel8 = new javax.swing.JPanel();
        emotionLabel1 = new javax.swing.JLabel();
        emotionLabel2 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTextArea5 = new javax.swing.JTextArea();
        jPanel7 = new javax.swing.JPanel();
        labelHeatmap1 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        jTextArea7 = new javax.swing.JTextArea();
        jPanel9 = new javax.swing.JPanel();
        labelHeatmap2 = new javax.swing.JLabel();
        jScrollPane6 = new javax.swing.JScrollPane();
        jTextArea6 = new javax.swing.JTextArea();
        jPanel10 = new javax.swing.JPanel();
        labelTopK1 = new javax.swing.JLabel();
        labelTopK2 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        jTextArea8 = new javax.swing.JTextArea();
        jScrollPane9 = new javax.swing.JScrollPane();
        jTextArea9 = new javax.swing.JTextArea();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1632, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 709, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1200, 900));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        labelTTR.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelTTR.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/TTR.png"))); // NOI18N
        labelTTR.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("Ross  avec un TTR-IDF de 0.00221:  signe d’un vocabulaire plus spécifique et rare \nChandler avec un TTR-IDF de 0.00214 : en cohérence avec son humour original\nPhoebe (0.00183) et Joey (0.00181) : une diversité modérée reflète le style direct\nRachel (0.00155) et Monica (0.00153) : TTR faible qui montre une langage partagé ou conventionnel\n");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTTR, javax.swing.GroupLayout.PREFERRED_SIZE, 903, Short.MAX_VALUE)
                    .addComponent(jScrollPane1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelTTR, javax.swing.GroupLayout.PREFERRED_SIZE, 378, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(779, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Taux de diversité lexicale ", jPanel1);

        labelPhoebe.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelPhoebe.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/phrasesrecuparss1.png"))); // NOI18N
        labelPhoebe.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelRoss.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelRoss.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/phrasesrecuparss2.png"))); // NOI18N
        labelRoss.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextArea2.setColumns(20);
        jTextArea2.setRows(5);
        jTextArea2.setText("Phoebe utilise beaucoup \"oh my god\", mais aussi des questions simples \ncomme \"what is that\".\nSon langage est direct, spontané et très expressif dès la première saison.");
        jScrollPane2.setViewportView(jTextArea2);

        jTextArea3.setColumns(20);
        jTextArea3.setRows(5);
        jTextArea3.setText("\"oh my god\" et \"i don't know\" sont les phrases les plus récurrentes.\nRoss montre une tendance à exprimer la surprise ou l’incertitude.\nCela correspond à sa personnalité anxieuse et souvent dépassée.");
        jScrollPane3.setViewportView(jTextArea3);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPhoebe, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2))
                .addGap(128, 128, 128)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 564, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelRoss, javax.swing.GroupLayout.PREFERRED_SIZE, 755, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelRoss, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labelPhoebe))
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE))
                .addContainerGap(819, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Phrases recurrentes par saison", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1316, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1359, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Profil Langagier", jPanel4);

        labelPrincipal.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        labelPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/perso_principal.png"))); // NOI18N

        jTextArea4.setColumns(20);
        jTextArea4.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea4.setRows(5);
        jTextArea4.setText("Nous avons mesuré le volume de mots prononcés par saison et par personnage.\n Ce graphique nous permet de repérer des évolutions marquantes.\nImplication centrale de Rachel en saison 7 et baisse notable de Chandler en saison 8. \nPhoebe est globalement la moins bavarde, ce qui peut refléter un rôle plus secondaire dans certaines saisons.");
        jScrollPane4.setViewportView(jTextArea4);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 1052, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane4))
                .addContainerGap(219, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(labelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, 422, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 800, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Personnage principal par saison", jPanel5);

        emotionLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/chandler_emotion.png"))); // NOI18N
        emotionLabel1.setText("jLabel3");

        emotionLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/monica_emotion.png"))); // NOI18N
        emotionLabel2.setText("jLabel4");

        jTextArea5.setColumns(20);
        jTextArea5.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea5.setRows(5);
        jTextArea5.setText("Utilisation du même modèle d’analyse émotionnelle que le groupe de sentiment (DistilBERT entraîné sur GoEmotions).\nCertaines associations sont très cohérentes (ex. \"I love you\" → amour), \nD’autres peuvent sembler discutables (ex. \"I don’t know\" → colère)\n->ce qui s’explique par les limites du modèle, qui ne prend pas en compte l’humour ou le ton du dialogue.");
        jScrollPane5.setViewportView(jTextArea5);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 1123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addComponent(emotionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(emotionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(emotionLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 427, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emotionLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(775, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Lien avec l'analyse sentimentale", jPanel8);

        labelHeatmap1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/heatmap1.png"))); // NOI18N
        labelHeatmap1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextArea7.setColumns(20);
        jTextArea7.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea7.setRows(5);
        jTextArea7.setText("Cette heatmap montre le nombre de mots communs utilisés entre\n chaque paire de personnages\n\nParmi les paires les plus proches : Joey–Chandler (2948) \ndevance légèrement Ross–Rachel (2929)\net Joey–Ross (2910), avec des écarts faibles mais notables. \n");
        jScrollPane7.setViewportView(jTextArea7);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(labelHeatmap1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 598, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(108, Short.MAX_VALUE)
                .addComponent(labelHeatmap1, javax.swing.GroupLayout.PREFERRED_SIZE, 487, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(764, 764, 764))
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(168, 168, 168)
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Nombre mots communs entre personnage", jPanel7);

        labelHeatmap2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        labelHeatmap2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/heatmap2.png"))); // NOI18N
        labelHeatmap2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextArea6.setColumns(20);
        jTextArea6.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea6.setRows(5);
        jTextArea6.setText("Mesure la ressemblance du vocabulaire \nutilisé entre chaque duo de personnages.\n\nPlus la valeur est proche de 1, plus les styles langagiers sont similaires.\n\nJoey et Ross ont la plus forte similarité lexicale (0.93)\n->ce qui reflète leur proximité scénaristique,");
        jScrollPane6.setViewportView(jTextArea6);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(labelHeatmap2, javax.swing.GroupLayout.PREFERRED_SIZE, 551, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 620, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(89, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(labelHeatmap2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(137, 137, 137)
                        .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(863, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Similarité langage", jPanel9);

        labelTopK1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/topk.png"))); // NOI18N
        labelTopK1.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelTopK2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ihm/images/topk2.png"))); // NOI18N
        labelTopK2.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        jTextArea8.setColumns(20);
        jTextArea8.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea8.setRows(5);
        jTextArea8.setText("Joey–Chandler : choix de mots distincts suggérant des manières de \nparler différentes\nVocabulaire peu croisé : reflète des sujets de conversation souvent \nséparés\nTonalité commune : langage amical et familier malgré les différences\n lexicales");
        jScrollPane8.setViewportView(jTextArea8);

        jTextArea9.setColumns(20);
        jTextArea9.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jTextArea9.setRows(5);
        jTextArea9.setText("Ross–Rachel : vocabulaire fortement centré sur le champ lexical de\n l’amour\nUsage fréquent de mots comme love, baby, married\n->montrant une expression émotionnelle marquée");
        jScrollPane9.setViewportView(jTextArea9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
                    .addComponent(labelTopK1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel10Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelTopK2, javax.swing.GroupLayout.PREFERRED_SIZE, 833, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(labelTopK1, javax.swing.GroupLayout.PREFERRED_SIZE, 397, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelTopK2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane8)
                    .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 192, Short.MAX_VALUE))
                .addContainerGap(731, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Top k mots", jPanel10);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1316, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FenetreGlobale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FenetreGlobale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FenetreGlobale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FenetreGlobale.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FenetreGlobale().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel emotionLabel1;
    private javax.swing.JLabel emotionLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextArea jTextArea2;
    private javax.swing.JTextArea jTextArea3;
    private javax.swing.JTextArea jTextArea4;
    private javax.swing.JTextArea jTextArea5;
    private javax.swing.JTextArea jTextArea6;
    private javax.swing.JTextArea jTextArea7;
    private javax.swing.JTextArea jTextArea8;
    private javax.swing.JTextArea jTextArea9;
    private javax.swing.JLabel labelHeatmap1;
    private javax.swing.JLabel labelHeatmap2;
    private javax.swing.JLabel labelPhoebe;
    private javax.swing.JLabel labelPrincipal;
    private javax.swing.JLabel labelRoss;
    private javax.swing.JLabel labelTTR;
    private javax.swing.JLabel labelTopK1;
    private javax.swing.JLabel labelTopK2;
    // End of variables declaration//GEN-END:variables
}



